name: jest-test
on:
  push:
    branches:
      - "**"
    branches-ignore:
      - main
    paths:
      - "js/**"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "**"
    branches-ignore:
      - main
    paths:
      - "js/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: 'npm'
      - name: change directory
        run: cd js
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
