name: jest-test
on:
  push:
    branches:
      - "**"
      - "!main"
    paths:
      - "js/**"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "**"
      - "!main"
    paths:
      - "js/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: Install dependencies
        working-directory: ./js
        run: npm install
      - name: Run tests
        working-directory: ./js
        run: npm test
